"use strict";
let a = 1;
a="JavaScript";
console.log(typeof a);
console.log(a);
console.log(typeof a);
let b;
console.log(b);
console.log(typeof b);
b="Jp";
console.log(c)
var c=10;
c=15;
console.log(c);
const d=6;
console.log(d);
const isAuthenticated=true;
console.log(isAuthenticated);
console.log(typeof isAuthenticated);
const isModalOpen = false;
console.log(isModalOpen);
console.log(typeof isModalOpen);
const guest=null;
console.log(null);
console.log(typeof null);
const message="hello!Great to meet you here!";
console.log(message);
let name="Student";
console.log(name);
console.log(`${name}, ${message}`);
//alert(`${name}, ${message}`);
//const isReady=confirm("Are you ready to stydy JavaScript?");
//console.log(isReady);
const enterName=prompt("Please,enter your name.");
console.log(enterName);